version: '2'
services:
 harvester:
    build: 
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
    volumes:
      - $XTRACTDIR:/output
    entrypoint: /usr/local/bin/istex-api-harvester
